### ISSUE TITLE
Activity Syntax for Compound that tells the mobile what to display in activities and the local notifications

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript-Examples#102]

**Comment by hboon** [comment]
Activity already uses a card's view and item-view, so this is just specifying a string which supports interpolation for attributes, right? eg.

"You have sent ${value} to ${to} successfully."

There might be a problem with ${value} not including decimals.

**Comment by James-Sangalli** [comment]
#108
