### ISSUE TITLE
Action views UI aave

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript-Examples#104]
https://app.zeplin.io/project/5eb4fcb5ce15ae774bd204bd/dashboard?tag=Aave

**Comment by hboon** [comment]
@tomekalphawallet can you grant me access to the Zeplin project?

**Comment by James-Sangalli** [comment]
@colourful-land would you be able to finish off the layouts for this one following the design here: https://app.zeplin.io/project/5eb4fcb5ce15ae774bd204bd/dashboard?tag=Aave

I have already created all the base layout files (in JS) with their corresponding TokenScripts and the blockchain information endpoints are already included. Just need the layouts completed.
