### ISSUE TITLE
Enable DAI to Aave activity bug

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript-Examples#125]
[Enabled DAI.pdf](https://github.com/AlphaWallet/TokenScript-Examples/files/4979942/Enabled.DAI.pdf)

**Comment by colourful-land** [comment]
Can you describe:

- how to reproduce
- what is expected

**Comment by zhangzhongnan928** [comment]
> Can you describe:
> 
> * how to reproduce
> * what is expected

all in the pdf
