### ISSUE TITLE
When schema 2020/03 is complete, migrate all the examples to the new format

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript-Examples#13]

**Comment by hboon** [comment]
In https://github.com/AlphaWallet/TokenScript-Examples/blob/4fc81a3e1b7443a3ce8c70ac9d49ef2789afdec7/examples/ENS/subdomainBundle.en.js#L15

There is this line:

```
document.getElementById("subdomainHash").innerHTML = namehash.hash(subdomain + "." + ensName);
```

Every call to `getElementById()` that is not passing in the container ID should be removed or replaced by a `getElementByClassName()` call instead.

**Comment by colourful-land** [comment]
@James-Sangalli should this be closed now?
