### ISSUE TITLE
Redesign action pages in karma

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript-Examples#32]
Follow this design: https://github.com/AlphaWallet/TokenScript/issues/317

You only need to adapt the existing pages, no need to change XML.

**Comment by ChintanRathod** [comment]
@James-Sangalli I went through the https://github.com/AlphaWallet/TokenScript/issues/317 issue but it is now too huge to understand what is expected. 
Can you point out which design I should work upon? 

![image](https://user-images.githubusercontent.com/4371780/77883273-67bc5e80-7280-11ea-84c3-bea26bf87c7b.png)

**Comment by James-Sangalli** [comment]
@ChintanRathod you have done screen 1, now you need to do screen 2-5.
