### ISSUE TITLE
This should be changed to cUSDC

### ISSUE THREAD

**Issue by coreycaplan3** [AlphaWallet/TokenScript-Examples#68]
https://github.com/AlphaWallet/TokenScript-Examples/blob/ceb97bfc676206df9e002928980f4d90b3847dd4/examples/erc20/DeFi/Compound/cUSDC.xml#L66

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/TokenScript-Examples/commit/605b2c93bc54cbeb0b1feb3f85046e744d88d50c
