### ISSUE TITLE
Nest Dividend time calculation is wrong

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript-Examples#83]
There is a time window of 60 hours for you to claim
    uint256 getAbonusTimeLimit = 60 hours;                          //  Trigger calculation settlement time
in 0xF67B829397Dc05751a98f243DbdE5Db63f86E7f6

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 are you saying my claim time is wrong or that once the claim time is open you only have 60 hours?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 are you saying my claim time is wrong or that once the claim time is open you only have 60 hours?

Once it open you only have 60 hours.

Currently, the TS works as "no time window" for claiming. 

For example, now TS shows " your dividend is not withdrawable yet, it will be in 583156 blocks"
But Nest Dapp shows"you can withdraw, and the collection countdown is 2days 5 h 57min 1s

**Comment by zhangzhongnan928** [comment]
There is still no time window( 60 hours) for you to claim.
In TS, once it hit 5th June, it started count for the next dividend time.


![IMG_3314](https://user-images.githubusercontent.com/33795543/83837565-1924b800-a73a-11ea-8b12-f761421917bf.PNG)
![IMG_EC6CDD37EFD4-1](https://user-images.githubusercontent.com/33795543/83837586-1d50d580-a73a-11ea-93bd-f45e649b2516.jpeg)
